import type { Metadata } from 'next';
import { Open_Sans } from 'next/font/google';

import './globals.css';

import Sidebar from '@/components/Sidebar';
import AuthContext from '@/context/AuthContext';
import SWRConfigContext from '@/context/SWRConfigContext';

const openSans = Open_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Instagram',
  description: 'Generated by Kangmuni',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={openSans.className}>
      <body className="flex flex-col w-full max-w-screen-2xl mx-auto">
        <AuthContext>
          <div className="flex h-screen">
            <Sidebar />
            <main className="w-full basis-11/12 m-9">
              <SWRConfigContext>{children}</SWRConfigContext>
            </main>
          </div>
        </AuthContext>
      </body>
    </html>
  );
}
